language: node_js
node_js:
  - "8"
cache:
  directories:
  - node_modules
script:
  - yarn build-storybook
  - cp -r .circleci storybook-static/
deploy:
  local_dir: storybook-static
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
