version: 2
jobs:
  hello-world:
    docker:
      - image: node:8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Hello world
          command: echo "Hello world"

workflows:
  version: 2
  build:
    jobs:
      - hello-world
